### ISSUE TITLE
Modern .NET 8

### ISSUE THREAD

**Issue by sjoerdev** [PPrism/TerrariaOGC#1]
would it be possible to make the project run on modern .net using [this](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant) tool?

**Comment by PPrism** [comment]
I don't see why not, I primarily kept it at 4.0 due to that being what it was at release.
My only concern for this would be the dependencies, so as long as FNA & Lidgren can work with it updated, it should be entirely functional (barring perhaps a few behavioural changes in the build process).

Would be worth to see if any of the known issues are resolved with it as well.

**Comment by sjoerdev** [comment]
i tried upgrading the project on my own, but i simply dont have a good enough understanding of the project and dependency structure yo make it work. can i pay you to upgrade the project to modern .net so i dont have to?

**Comment by PPrism** [comment]
Ok, 1. Not taking payment for this, and 2. I might take a look when I have some time & energy about whether a fork could be worth it for an updated .NET version

**Comment by PPrism** [comment]
Ok, I should have realised this when I looked at it, but modern .NET is not an option here, since what TerrariaOGC requires, along with even normal Terraria, is the XNA framework. 

This depends on the .NET Framework so I do not believe it is possible to update to modern .NET versions and retain functionality, since XNA will no longer work.

**Comment by PPrism** [comment]
Well the idea was to at least keep it with the ability to run with the original XNA framework and I didn't want to complicate setup too much by adding an entirely different version of the project, but I'll still give it a shot, see whats different.

**Comment by sjoerdev** [comment]
fna should be a drag and drop replacement of xna. it even keeps the same namespace names.

**Comment by PPrism** [comment]
I'm quite a busy person so in terms of a 'complete' transition to .NET, no, I have not had time to do so.
I did make some progress although I believe that is as far as it can go. 
.NET makes far too many dependencies non-functional.

Using .NET8, no differences can be seen, although attempting to start a world leads to numerous errors regarding the session being created due to the behind-the-scenes network code not operating. This is also looking past the numerous edits I had to make to the code to account for obsolete differences (e.g, different achievement handler due to no Newtonsoft).

Since for this to go any further, it would need someone to completely excise network elements or to make completely operational network code for FNA, I'll leave it at this for now.

**Comment by sjoerdev** [comment]
@PPrism But without the networking functionallity it does work with modern .net? can i see the codebase of the transition so far?

**Comment by sjoerdev** [comment]
I can't expect you to just do all of that required work. and i dont expect you too. 
so maybe someone can be hired to do the work?
how much do you think it would cost in total to hire people to make the transition fully to modern .net?

**Comment by PPrism** [comment]
I do not know how much because I will never be hiring someone to do that kind of work for this project, not to mention it goes outside the scope of this project. The only time I would actively consider a modern .NET transition is after the 1.09 update is ported over.

Currently, the only work I will be doing on this project is the porting of 1.03 or decompilation of E.NET.
